[package]
name = "ovba"
version = "0.1.0"
authors = ["Tim Weis <tim.weis@outlook.com>"]
description = "Library for inspecting and extracting data from Office Open XML VBA projects."
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfb = "0.3"
codepage = "0.1"
encoding_rs = "0.8"
nom = "5.1"
thiserror = "1"

[workspace]
members = ["cli-tool/"]
