name: continuous-integration
on:
  [push, pull_request]

jobs:
  check-formatting:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt

    - run: cargo fmt --verbose -- check
