name: continuous-integration
on:
  [push, pull_request]

env:
  RUST_BACKTRACE: 1

jobs:
  rustfmt:
    name: Verify code formatting
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, clippy

    - run: cargo fmt --all -- --check
